function make_placeholder(parent, title_txt, msg_txt)
%MAKE_PLACEHOLDER  Centered empty-state card (Tag 'placeholder') shown in a
%   Results panel before any figures have been embedded.
pos = parent.Position;
W = min(520, pos(3) - 40);  H = 120;
card = uipanel(parent,'Tag','placeholder','BorderType','line', ...
    'BackgroundColor',[0.93 0.91 0.87], ...
    'Position',[round((pos(3)-W)/2) round((pos(4)-H)/2) W H]);
if isprop(card,'BorderColor'), card.BorderColor = [0.81 0.73 0.57]; end
uipanel(card,'BorderType','none','BackgroundColor',[0.81 0.73 0.57], ...
    'Position',[0 H-6 W 6]);
uilabel(card,'Text',title_txt,'FontSize',20,'FontWeight','bold', ...
    'FontColor',[0.08 0.08 0.08],'HorizontalAlignment','center', ...
    'Position',[10 H-56 W-20 34]);
uilabel(card,'Text',msg_txt,'FontSize',14,'FontColor',[0.45 0.45 0.45], ...
    'HorizontalAlignment','center','WordWrap','on', ...
    'Position',[10 12 W-20 44]);
end
