function createComponents(app)
%CREATECOMPONENTS  Build all UI components for APAT_app.
%   Creates the figure window, black header bar, and three tabs:
%   Setup, Results, Status. Each tab is built by a local function.

app.clr_black   = [0.08 0.08 0.08];
app.clr_gold    = [0.81 0.73 0.57];
app.clr_gold_dk = [0.55 0.42 0.12];
app.clr_bg      = [0.97 0.96 0.93];
app.clr_panel   = [0.93 0.91 0.87];
app.clr_btn     = [0.86 0.84 0.79];

PAD   = 8;
HDR_H = 110;

scr   = get(0,'ScreenSize');
FIG_W = scr(3);
FIG_H = scr(4) - 50;
TAB_H = FIG_H - HDR_H;

app.UIFigure = uifigure( ...
    'Name','Auditory Physiology Analysis Toolkit (APAT)', ...
    'WindowState','maximized', ...
    'Color',app.clr_bg, ...
    'CloseRequestFcn',@(~,~) delete(app));

% ── Header ─────────────────────────────────────────────────────────────
app.HeaderPanel = uipanel(app.UIFigure, ...
    'BorderType','none','BackgroundColor',app.clr_black, ...
    'Position',[0 FIG_H-HDR_H FIG_W HDR_H]);

app.TitleLabel = uilabel(app.HeaderPanel, ...
    'Text','Auditory Physiology Analysis Toolkit (APAT)', ...
    'Position',[16 54 FIG_W-250 36], ...
    'FontSize',26,'FontWeight','bold','FontColor',app.clr_gold);

app.SubtitleLabel = uilabel(app.HeaderPanel, ...
    'Text','Auditory Neurophysiology and Modeling Lab  —  Purdue University', ...
    'Position',[16 30 FIG_W-250 22], ...
    'FontSize',15,'FontColor',[0.88 0.84 0.74]);

RUN_W = 190;  RUN_H = 46;
app.RunButton = uibutton(app.HeaderPanel,'push', ...
    'Text','▶  Run Analysis', ...
    'Position',[FIG_W-RUN_W-16 round((HDR_H-RUN_H)/2) RUN_W RUN_H], ...
    'FontSize',16,'FontWeight','bold', ...
    'FontColor',app.clr_black,'BackgroundColor',app.clr_gold, ...
    'ButtonPushedFcn',@(~,~) RunButtonPushed(app));

RUN_X  = FIG_W - RUN_W - 16;
RUN_Y  = round((HDR_H - RUN_H) / 2);
STOP_W = 120;  STOP_H = RUN_H;
SPIN_W = 30;   SPIN_H = 30;
LBL_H  = 16;
STOP_X = RUN_X - STOP_W - 10;
SPIN_X = STOP_X - SPIN_W - 10;
SPIN_Y = RUN_Y + round((RUN_H - SPIN_H) / 2);
LBL_Y  = RUN_Y - LBL_H - 3;

app.StopButton = uibutton(app.HeaderPanel,'push', ...
    'Text','■  Stop', ...
    'Position',[STOP_X RUN_Y STOP_W STOP_H], ...
    'FontSize',16,'FontWeight','bold', ...
    'FontColor',app.clr_black,'BackgroundColor',[0.78 0.28 0.28], ...
    'Visible','off','Enable','on', ...
    'ButtonPushedFcn',@(~,~) StopButtonPushed(app));

app.h_spinner_label = uilabel(app.HeaderPanel, ...
    'Text','','FontSize',18,'FontColor',app.clr_gold, ...
    'HorizontalAlignment','center', ...
    'Position',[SPIN_X SPIN_Y SPIN_W SPIN_H],'Visible','off');

app.h_progress_label = uilabel(app.HeaderPanel, ...
    'Text','','FontSize',10,'FontColor',[0.78 0.74 0.64], ...
    'HorizontalAlignment','center', ...
    'Position',[RUN_X LBL_Y RUN_W LBL_H],'Visible','off');

app.spinner_frame   = 1;
app.abort_requested = false;

% ── Tab group ────────────────────────────────────────────────────────────
app.TabGroup = uitabgroup(app.UIFigure,'Position',[0 0 FIG_W TAB_H]);
app.SetupTab   = uitab(app.TabGroup,'Title','  Setup  ');
app.ResultsTab = uitab(app.TabGroup,'Title','  Results  ');
app.StatusTab  = uitab(app.TabGroup,'Title','  Data Status  ');
app.SetupTab.BackgroundColor   = app.clr_bg;
app.ResultsTab.BackgroundColor = app.clr_bg;
app.StatusTab.BackgroundColor  = app.clr_bg;

buildSetupTab(app,   PAD, FIG_W, TAB_H);
buildResultsTab(app, PAD, FIG_W, TAB_H);
buildStatusTab(app,  PAD, FIG_W, TAB_H);
buildPeakEditPanel(app, FIG_W, TAB_H);
end


% ══════════════════════════════════════════════════════════════════════════
%  TAB BUILDERS
% ══════════════════════════════════════════════════════════════════════════

function buildSetupTab(app, PAD, FIG_W, TAB_H)
FS  = 15;
CH  = 30;
LH  = 24;

ROW1_H = 4*CH + 2*PAD + 20;
ROW2_H = 5*CH + 2*PAD + 20;
MEAS_H = max(100, TAB_H - 30 - PAD - ROW1_H - PAD - ROW2_H - PAD - PAD);

app.layout_row2_h = ROW2_H;
app.layout_meas_h = MEAS_H;

meas_y = PAD;
row2_y = meas_y + MEAS_H + PAD;
row1_y = row2_y + ROW2_H + PAD;

USER_W = 240;
SP_X   = PAD + USER_W + PAD;
SP_W   = FIG_W - SP_X - PAD;

% ── User panel ──────────────────────────────────────────────────────────
app.UserPanel = uipanel(app.SetupTab, ...
    'Title','User','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[PAD row1_y USER_W ROW1_H]);

inner_w = USER_W - 22;
y3 = ROW1_H - 30 - CH;
y2 = y3 - PAD - CH;
y1 = y2 - PAD - CH;
app.ProfileDropdown = uidropdown(app.UserPanel, ...
    'Items',{'(no profiles)'},'Value','(no profiles)', ...
    'Position',[8 y3 inner_w CH], ...
    'FontSize',FS,'FontWeight','bold', ...
    'ValueChangedFcn',@(~,~) ProfileDropdownChanged(app));
app.NewUserBtn = uibutton(app.UserPanel,'push','Text','New User', ...
    'Position',[8 y2 inner_w CH],'FontSize',FS,'BackgroundColor',app.clr_btn, ...
    'ButtonPushedFcn',@(~,~) NewUserButtonPushed(app));
app.SaveUserBtn = uibutton(app.UserPanel,'push','Text','Save User', ...
    'Position',[8 y1 inner_w CH],'FontSize',FS,'BackgroundColor',app.clr_btn, ...
    'ButtonPushedFcn',@(~,~) SaveUserButtonPushed(app));

% ── Project settings panel ──────────────────────────────────────────────
app.ProjectPanel = uipanel(app.SetupTab, ...
    'Title','Project Settings','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[SP_X row1_y SP_W ROW1_H]);

LBL_W  = 140;  CTRL_X = LBL_W + 8;  CTRL_W = SP_W - CTRL_X - 14;
py3 = ROW1_H - 30 - CH;
py2 = py3 - PAD - CH;
py1 = py2 - PAD - CH;
uilabel(app.ProjectPanel,'Text','Root Directory:', ...
    'Position',[8 py3 LBL_W LH],'FontSize',FS);
app.RootDirField = uieditfield(app.ProjectPanel,'text','Value','', ...
    'Position',[CTRL_X py3 CTRL_W-100 CH],'FontSize',FS,'BackgroundColor','white');
app.BrowseBtn = uibutton(app.ProjectPanel,'push','Text','Browse...', ...
    'Position',[CTRL_X+CTRL_W-96 py3 96 CH],'FontSize',FS,'BackgroundColor',app.clr_btn, ...
    'ButtonPushedFcn',@(~,~) BrowseButtonPushed(app));
uilabel(app.ProjectPanel,'Text','Subject Roster:', ...
    'Position',[8 py2 LBL_W LH],'FontSize',FS);
app.RosterDropdown = uidropdown(app.ProjectPanel, ...
    'Items',{'(set root directory first)'},'Value','(set root directory first)', ...
    'Position',[CTRL_X py2 CTRL_W CH],'FontSize',FS, ...
    'ValueChangedFcn',@(~,~) RosterDropdownChanged(app));
uilabel(app.ProjectPanel,'Text','Experiment:', ...
    'Position',[8 py1 LBL_W LH],'FontSize',FS);
app.SheetDropdown = uidropdown(app.ProjectPanel, ...
    'Items',{'(load chinroster first)'},'Value','(load chinroster first)', ...
    'Position',[CTRL_X py1 round(CTRL_W*0.6) CH], ...
    'FontSize',FS+1,'FontWeight','bold', ...
    'ValueChangedFcn',@(~,~) SheetDropdownChanged(app));

% ── Subjects panel ──────────────────────────────────────────────────────
subj_w  = round((FIG_W - 3*PAD) * 0.55);
right_w = FIG_W - 3*PAD - subj_w;
opt_w2  = max(220, round(right_w * 0.40));
cond_w  = right_w - PAD - opt_w2;

app.SubjectsPanel = uipanel(app.SetupTab, ...
    'Title','Subjects','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[PAD row2_y subj_w ROW2_H]);

BTN_W3 = round((subj_w - 4*PAD) / 3);
app.SelectAllBtn = uibutton(app.SubjectsPanel,'push','Text','Select All', ...
    'Position',[PAD PAD BTN_W3 CH],'FontSize',FS,'BackgroundColor',app.clr_btn, ...
    'ButtonPushedFcn',@(~,~) SelectAllButtonPushed(app));
app.ClearSubjBtn = uibutton(app.SubjectsPanel,'push','Text','Clear', ...
    'Position',[2*PAD+BTN_W3 PAD BTN_W3 CH],'FontSize',FS,'BackgroundColor',app.clr_btn, ...
    'ButtonPushedFcn',@(~,~) ClearButtonPushed(app));
app.RefreshSubjBtn = uibutton(app.SubjectsPanel,'push','Text','Refresh', ...
    'Position',[3*PAD+2*BTN_W3 PAD BTN_W3 CH],'FontSize',FS,'BackgroundColor',app.clr_btn, ...
    'ButtonPushedFcn',@(~,~) RefreshButtonPushed(app));

% ── Conditions panel ────────────────────────────────────────────────────
app.ConditionsPanel = uipanel(app.SetupTab, ...
    'Title','Conditions','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[PAD+subj_w+PAD row2_y cond_w ROW2_H]);

% ── Options panel ───────────────────────────────────────────────────────
opt_x = PAD + subj_w + PAD + cond_w + PAD;
app.OptionsPanel = uipanel(app.SetupTab, ...
    'Title','Options','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[opt_x row2_y opt_w2 ROW2_H]);

ck_labels   = {'Re-analyze existing data','Plot relative to Baseline'};
ck_defaults = [true false];
ck_handles  = {'ReanalyzeCheck','PlotRelativeCheck'};
n_ck   = numel(ck_labels);
ck_avail = ROW2_H - 38 - 8;
ck_gap   = max(2, (ck_avail - n_ck*CH) / (n_ck + 1));
for ci = 1:n_ck
    cy = 8 + (n_ck - ci) * (CH + ck_gap) + ck_gap;
    app.(ck_handles{ci}) = uicheckbox(app.OptionsPanel, ...
        'Text',ck_labels{ci},'Value',ck_defaults(ci), ...
        'Position',[10 round(cy) opt_w2-20 CH],'FontSize',FS);
end

% ── Auditory Measures panel ──────────────────────────────────────────────
app.MeasuresPanel = uipanel(app.SetupTab, ...
    'Title','Auditory Measures','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[PAD meas_y FIG_W-2*PAD MEAS_H]);

panel_w  = FIG_W - 2*PAD;
DESC_X   = round(0.52 * panel_w);
DESC_W   = max(200, round(panel_w * 0.20));
RIGHT_X  = DESC_X + DESC_W + 12;
RIGHT_W  = max(300, panel_w - RIGHT_X - PAD);

app.DescTitleLabel = uilabel(app.MeasuresPanel,'Text','', ...
    'Position',[DESC_X round(0.60*MEAS_H) DESC_W round(0.09*MEAS_H)], ...
    'FontSize',FS,'FontWeight','bold','FontColor',app.clr_black);
app.DescLabel = uilabel(app.MeasuresPanel,'Text','', ...
    'Position',[DESC_X round(0.05*MEAS_H) DESC_W round(0.51*MEAS_H)], ...
    'FontSize',FS,'FontColor',app.clr_gold_dk,'WordWrap','on');

app.h_meas_btns = gobjects(0);
app.h_sub_btns  = {};

buildMeasureButtons(app, panel_w, MEAS_H);
buildParamPanels(app, RIGHT_X, RIGHT_W, MEAS_H, PAD, FS, LH);
end


function buildMeasureButtons(app, panel_w, MEAS_H)
%BUILDMEASUREBUTTONS  Create major measure and subtype buttons in MeasuresPanel.
app.n_meas   = length(app.MEASURES);
app.meas_h   = 0.22;
app.meas_gap = 0.02;

MEAS_BTN_W = max(110, min(150, round(0.12*panel_w)));
app.h_meas_btns = gobjects(1, app.n_meas);
app.h_sub_btns  = cell(1, app.n_meas);

for m = 1:app.n_meas
    y_m = 0.99 - m*(app.meas_h + app.meas_gap) + app.meas_gap;
    app.h_meas_btns(m) = uibutton(app.MeasuresPanel,'push', ...
        'Text',app.MEASURES(m).name, ...
        'Position',[round(0.01*panel_w) round(y_m*MEAS_H) MEAS_BTN_W round(app.meas_h*MEAS_H)], ...
        'FontSize',20,'FontWeight','bold','BackgroundColor',app.clr_btn, ...
        'UserData',m, ...
        'ButtonPushedFcn',@(src,~) MeasureButtonPushed(app, src));
end

% Gold vertical divider
div_x = round(0.01*panel_w) + MEAS_BTN_W + 4;
uipanel(app.MeasuresPanel,'BorderType','none','BackgroundColor',app.clr_gold, ...
    'Position',[div_x round(0.02*MEAS_H) 3 round(0.94*MEAS_H)]);

% Subtype buttons
SUB_START_PX = div_x + 10;
app.meas_sub_area_start = SUB_START_PX;
SUB_END = 0.50;
for m = 1:app.n_meas
    y_m  = 0.99 - m*(app.meas_h + app.meas_gap) + app.meas_gap;
    subs = app.MEASURES(m).subtypes;
    app.h_sub_btns{m} = gobjects(1, max(1,numel(subs)));
    if ~isempty(subs)
        sub_area_px = round(SUB_END * panel_w) - SUB_START_PX;
        sub_btn_w   = max(120, floor(sub_area_px / numel(subs)) - 4);
        for k = 1:numel(subs)
            app.h_sub_btns{m}(k) = uibutton(app.MeasuresPanel,'push', ...
                'Text',subs{k}, ...
                'Position',[SUB_START_PX + (k-1)*(sub_btn_w+4) round(y_m*MEAS_H) sub_btn_w round(app.meas_h*MEAS_H)], ...
                'FontSize',18,'BackgroundColor',app.clr_btn,'Visible','off', ...
                'UserData',[m k], ...
                'ButtonPushedFcn',@(src,~) SubtypeButtonPushed(app, src));
        end
    end
end
end


function buildParamPanels(app, RIGHT_X, RIGHT_W, MEAS_H, PAD, FS, LH)
%BUILDPARAMPANELS  Create ABR/EFR/OAE/MEMR parameter panels (hidden by default).
INNER_H     = 470;
ABR_OUTER_H = min(INNER_H, max(220, MEAS_H - 10));
ABR_PANEL_Y = round((MEAS_H - ABR_OUTER_H) / 2);
inner_rw    = RIGHT_W - 2*PAD;
SECT_GAP    = 16;

% ── ABR Parameters ────────────────────────────────────────────────────────
app.h_abr_param_panel = uipanel(app.MeasuresPanel, ...
    'Title','ABR Parameters','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[RIGHT_X ABR_PANEL_Y RIGHT_W ABR_OUTER_H], ...
    'Scrollable','on','Visible','off');

freq_labels = {'Click','0.5 kHz','1 kHz','2 kHz','4 kHz','8 kHz'};
n_freq = numel(freq_labels);
ck_w   = max(60, floor(inner_rw / n_freq));
FREQ_Y  = INNER_H - 40 - 30;
FREQ_LY = FREQ_Y + 30 + 4;
uilabel(app.h_abr_param_panel,'Text','Frequencies:', ...
    'Position',[PAD FREQ_LY inner_rw LH],'FontSize',FS,'FontWeight','bold');
app.h_abr_freq_checks = gobjects(1, n_freq);
for fi = 1:n_freq
    app.h_abr_freq_checks(fi) = uicheckbox(app.h_abr_param_panel, ...
        'Text',freq_labels{fi},'Value',true, ...
        'Position',[PAD+(fi-1)*ck_w FREQ_Y ck_w-2 30],'FontSize',FS-1);
end

level_labels = {'80 dB','70 dB','60 dB','50 dB','40 dB'};
n_lev  = numel(level_labels);
lev_w  = max(60, floor(inner_rw / n_lev));
LEV_Y  = FREQ_Y - SECT_GAP - LH - 30;
LEV_LY = LEV_Y + 30 + 4;
uilabel(app.h_abr_param_panel,'Text','Levels:', ...
    'Tag','abr_lev_lbl', ...
    'Position',[PAD LEV_LY inner_rw LH],'FontSize',FS,'FontWeight','bold');
app.h_abr_level_checks = gobjects(1, n_lev);
for li = 1:n_lev
    app.h_abr_level_checks(li) = uicheckbox(app.h_abr_param_panel, ...
        'Text',level_labels{li},'Value',true, ...
        'Position',[PAD+(li-1)*lev_w LEV_Y lev_w-2 30],'FontSize',FS-1);
end

wave_labels = {'W I','W II','W III','W IV','W V'};
n_wave    = numel(wave_labels);
wave_ck_w = max(48, floor(inner_rw / n_wave));
WAVE_Y  = LEV_Y - SECT_GAP - LH - 30;
WAVE_LY = WAVE_Y + 30 + 4;
uilabel(app.h_abr_param_panel,'Text','Waves:', ...
    'Tag','abr_wave_lbl', ...
    'Position',[PAD WAVE_LY inner_rw LH],'FontSize',FS,'FontWeight','bold');
app.h_abr_wave_checks = gobjects(1, n_wave);
for wi = 1:n_wave
    app.h_abr_wave_checks(wi) = uicheckbox(app.h_abr_param_panel, ...
        'Text',wave_labels{wi},'Value',true,'Tag','abr_wave_ck', ...
        'Position',[PAD+(wi-1)*wave_ck_w WAVE_Y wave_ck_w-2 30],'FontSize',FS-1);
end


% ── EFR Parameters ────────────────────────────────────────────────────────
app.h_efr_param_panel = uipanel(app.MeasuresPanel, ...
    'Title','EFR Parameters','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[RIGHT_X ABR_PANEL_Y RIGHT_W ABR_OUTER_H], ...
    'Scrollable','on','Visible','off');

uilabel(app.h_efr_param_panel,'Text','RAM — configurable:', ...
    'Tag','efr_ram_hdr','Position',[PAD INNER_H-40 inner_rw LH],'FontSize',FS,'FontWeight','bold');
uilabel(app.h_efr_param_panel,'Text','Mod. freq: 223 Hz  |  Filter: 60–4000 Hz', ...
    'Tag','efr_ram_info','Position',[PAD INNER_H-65 inner_rw LH],'FontSize',FS-2,'FontColor',[0.5 0.5 0.5]);

HARM_Y  = INNER_H - 100 - 30;
HARM_LY = HARM_Y + 30 + 4;
uilabel(app.h_efr_param_panel,'Text','Max harmonics (1–16):', ...
    'Tag','efr_harm_lbl','Position',[PAD HARM_LY inner_rw LH],'FontSize',FS,'FontWeight','bold');
app.h_efr_harmonics_field = uieditfield(app.h_efr_param_panel,'numeric', ...
    'Value',16,'Limits',[1 16],'RoundFractionalValues','on','Tag','efr_harmonics', ...
    'Position',[PAD HARM_Y 80 30],'FontSize',FS,'BackgroundColor','white');

WIN_Y  = HARM_Y - SECT_GAP - LH - 30;
WIN_LY = WIN_Y + 30 + 4;
uilabel(app.h_efr_param_panel,'Text','Analysis window (s):', ...
    'Tag','efr_win_lbl','Position',[PAD WIN_LY inner_rw LH],'FontSize',FS,'FontWeight','bold');
uilabel(app.h_efr_param_panel,'Text','Start:', ...
    'Tag','efr_win_s_lbl','Position',[PAD WIN_Y 38 30],'FontSize',FS-2);
app.h_efr_window_start_field = uieditfield(app.h_efr_param_panel,'numeric', ...
    'Value',0.2,'Limits',[0 2],'Tag','efr_win_start', ...
    'Position',[PAD+42 WIN_Y 60 30],'FontSize',FS-2,'BackgroundColor','white');
uilabel(app.h_efr_param_panel,'Text','End:', ...
    'Tag','efr_win_e_lbl','Position',[PAD+116 WIN_Y 36 30],'FontSize',FS-2);
app.h_efr_window_end_field = uieditfield(app.h_efr_param_panel,'numeric', ...
    'Value',0.9,'Limits',[0 2],'Tag','efr_win_end', ...
    'Position',[PAD+156 WIN_Y 60 30],'FontSize',FS-2,'BackgroundColor','white');

DAM_HDR_Y = WIN_Y - SECT_GAP - LH;
uilabel(app.h_efr_param_panel,'Text','dAM — fixed parameters:', ...
    'Position',[PAD DAM_HDR_Y inner_rw LH],'FontSize',FS,'FontWeight','bold');
uilabel(app.h_efr_param_panel,'Text', ...
    'Carrier: 4 kHz  |  AM sweep: 4–10.5 Hz  |  Demod filter: 10–1500 Hz', ...
    'Position',[PAD DAM_HDR_Y-LH inner_rw LH],'FontSize',FS-2,'FontColor',[0.5 0.5 0.5]);

% ── OAE Parameters ────────────────────────────────────────────────────────
app.h_oae_param_panel = uipanel(app.MeasuresPanel, ...
    'Title','OAE Parameters','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[RIGHT_X ABR_PANEL_Y RIGHT_W ABR_OUTER_H], ...
    'Scrollable','on','Visible','off');
uilabel(app.h_oae_param_panel,'Text','All OAE: FPL (Forward Pressure Level) calibration', ...
    'Position',[PAD INNER_H-40 inner_rw LH],'FontSize',FS-1,'FontWeight','bold');
uilabel(app.h_oae_param_panel,'Text','DPOAE:', ...
    'Position',[PAD INNER_H-80 inner_rw LH],'FontSize',FS,'FontWeight','bold');
uilabel(app.h_oae_param_panel,'Text', ...
    'Analysis window: 0.25 s  |  f2/f1 = 1.2  |  FFT: 512 pts  |  Upward sweep', ...
    'Position',[PAD INNER_H-105 inner_rw LH],'FontSize',FS-2,'FontColor',[0.5 0.5 0.5]);
uilabel(app.h_oae_param_panel,'Text','SFOAE:', ...
    'Position',[PAD INNER_H-145 inner_rw LH],'FontSize',FS,'FontWeight','bold');
uilabel(app.h_oae_param_panel,'Text','Downward frequency sweep  |  FPL calibration', ...
    'Position',[PAD INNER_H-170 inner_rw LH],'FontSize',FS-2,'FontColor',[0.5 0.5 0.5]);
uilabel(app.h_oae_param_panel,'Text','TEOAE:', ...
    'Position',[PAD INNER_H-210 inner_rw LH],'FontSize',FS,'FontWeight','bold');
uilabel(app.h_oae_param_panel,'Text','Stimulus: click  |  FPL calibration', ...
    'Position',[PAD INNER_H-235 inner_rw LH],'FontSize',FS-2,'FontColor',[0.5 0.5 0.5]);

% ── MEMR Parameters ───────────────────────────────────────────────────────
app.h_memr_param_panel = uipanel(app.MeasuresPanel, ...
    'Title','MEMR Parameters','FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_panel,'BorderColor',app.clr_gold, ...
    'Position',[RIGHT_X ABR_PANEL_Y RIGHT_W ABR_OUTER_H], ...
    'Scrollable','on','Visible','off');
uilabel(app.h_memr_param_panel,'Text','Wideband Middle Ear Muscle Reflex', ...
    'Position',[PAD INNER_H-40 inner_rw LH],'FontSize',FS,'FontWeight','bold');
uilabel(app.h_memr_param_panel,'Text','Frequency range: 0.2–8 kHz', ...
    'Position',[PAD INNER_H-80 inner_rw LH],'FontSize',FS-1,'FontColor',[0.5 0.5 0.5]);
uilabel(app.h_memr_param_panel,'Text','Metric: Δ absorbed sound power (dB) vs. elicitor level', ...
    'Position',[PAD INNER_H-110 inner_rw LH],'FontSize',FS-1,'FontColor',[0.5 0.5 0.5]);
uilabel(app.h_memr_param_panel,'Text','Elicitor: broadband noise, multiple levels', ...
    'Position',[PAD INNER_H-140 inner_rw LH],'FontSize',FS-1,'FontColor',[0.5 0.5 0.5]);
uilabel(app.h_memr_param_panel,'Text','Output: growth functions and reflex thresholds', ...
    'Position',[PAD INNER_H-170 inner_rw LH],'FontSize',FS-1,'FontColor',[0.5 0.5 0.5]);
end


function buildResultsTab(app, ~, FIG_W, TAB_H)
%BUILDRESULTSTAB  Results tab: 8 measure buttons + mode toggle + figure panels.
PAD    = 10;
FS     = 15;
ROW_H  = 50;
CTRL_H = ROW_H + 2*PAD;
PLOT_H = TAB_H - 30 - CTRL_H;
y1     = PAD;

ctrl = uipanel(app.ResultsTab,'BorderType','none', ...
    'BackgroundColor',app.clr_panel,'Position',[0 PLOT_H FIG_W CTRL_H]);

% ── Mode buttons ─────────────────────────────────────────────────────────
x = 2*PAD;
app.FigAvgBtn = uibutton(ctrl,'state','Text','Average','Value',true, ...
    'FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_gold,'FontColor',app.clr_black, ...
    'Position',[x y1 104 ROW_H], ...
    'ValueChangedFcn',@(~,~) navigate_results(app,'avg'));

x = x + 104 + PAD;
app.FigIndBtn = uibutton(ctrl,'state','Text','Individual','Value',false, ...
    'FontSize',FS,'FontWeight','bold', ...
    'BackgroundColor',app.clr_btn,'FontColor',app.clr_black, ...
    'Position',[x y1 120 ROW_H], ...
    'ValueChangedFcn',@(~,~) navigate_results(app,'ind'));

x = x + 120 + PAD;
app.FigSubjDropdown = uidropdown(ctrl, ...
    'Items',{'-'},'Value','-', ...
    'FontSize',FS,'Position',[x y1+5 90 ROW_H-10],'Visible','off', ...
    'ValueChangedFcn',@(~,~) navigate_results(app,'subj'));

x = x + 90 + PAD;
% Divider
uipanel(ctrl,'BorderType','none','BackgroundColor',app.clr_gold,'Position',[x y1+4 2 ROW_H-8]);
x = x + 2*PAD;

% ── 8 measure buttons (grouped with thin separators between groups) ─────
labels = APAT_app.measure_tab_labels();
% groups = {1:2, 3:4, 5:7, 8}  — ABR | EFR | OAE | MEMR
groups   = {[1 2],[3 4],[5 6 7],[8]};
BTN_W    = 120;
SHORT_W  = 80;
app.res.btns = gobjects(1, numel(labels));

for gi = 1:numel(groups)
    grp = groups{gi};
    for k = 1:numel(grp)
        idx  = grp(k);
        lbl  = labels{idx};
        bw   = ternary(numel(lbl) <= 5, SHORT_W, BTN_W);
        is_first = (gi==1 && k==1);
        btn = uibutton(ctrl,'push','Text',lbl, ...
            'FontSize',FS-1,'FontWeight','bold', ...
            'BackgroundColor',ternary(is_first,app.clr_gold,app.clr_btn), ...
            'FontColor',app.clr_black, ...
            'Position',[x y1 bw ROW_H], ...
            'UserData',idx, ...
            'ButtonPushedFcn',@(~,~) navigate_results(app,'meas_btn',idx));
        app.res.btns(idx) = btn;
        x = x + bw + PAD;
    end
    % Thin gold divider between groups (not after last)
    if gi < numel(groups)
        uipanel(ctrl,'BorderType','none','BackgroundColor',app.clr_gold, ...
            'Position',[x y1+4 2 ROW_H-8]);
        x = x + PAD + 2;
    end
end

% ── Freq/Cond dropdown ────────────────────────────────────────────────────
x = x + PAD;
uilabel(ctrl,'Tag','fig_freq_lbl','Text','Frequency:', ...
    'FontSize',FS,'Visible','off','Position',[x y1+16 82 20]);
x = x + 84;
app.FigFreqDD = uidropdown(ctrl, ...
    'Items',{'—'},'Value','—', ...
    'FontSize',FS,'Visible','off','Position',[x y1+6 148 ROW_H-12], ...
    'ValueChangedFcn',@(~,~) navigate_results(app,'freq'));

% ── Figure panels: 2 modes × 8 measures (stacked, one visible at a time) ──
N_MEAS = numel(labels);
app.res.panels   = cell(2, N_MEAS);
app.res.subj_data = cell(1, N_MEAS);
for mi = 1:N_MEAS
    app.res.subj_data{mi} = struct('names',{{}},'panels',{{}});
end
for mode = 1:2
    for mi = 1:N_MEAS
        p = uipanel(app.ResultsTab,'BorderType','none','BackgroundColor',app.clr_bg, ...
            'Position',[0 0 FIG_W PLOT_H],'Visible','off');
        if mode == 2
            uilabel(p,'Tag','placeholder', ...
                'Text','No figures to show :(\n\n Run analysis.', ...
                'Position',[0 round(PLOT_H/2-30) FIG_W 60], ...
                'FontSize',18,'FontColor',[0.55 0.55 0.55], ...
                'HorizontalAlignment','center','WordWrap','on');
        end
        app.res.panels{mode,mi} = p;
    end
end
% Start in Average mode, measure 1 (ABR Thresholds)
app.res.mode     = 2;
app.res.meas_idx = 1;
app.res.panels{2,1}.Visible = 'on';
end


function buildStatusTab(app, PAD, FIG_W, TAB_H)
INNER_H = TAB_H - 30;
BTN_H   = 40;
TG_H    = INNER_H - BTN_H - 2*PAD;

app.RefreshStatusBtn = uibutton(app.StatusTab,'push','Text','⟳  Refresh', ...
    'Position',[PAD TG_H+PAD 110 BTN_H],'FontSize',16, ...
    'BackgroundColor',app.clr_btn, ...
    'ButtonPushedFcn',@(~,~) RefreshStatusButtonPushed(app));

app.StatusInnerTG = uitabgroup(app.StatusTab,'Position',[0 0 FIG_W TG_H]);
end


function buildPeakEditPanel(app, FIG_W, TAB_H)
%BUILDPEAKEDITPANEL  Full-area overlay shown during interactive ABR peak editing.
%   Covers the entire tab region, sits above the TabGroup in z-order.
%   Controlled by findPeaks_dtw via peak_ui struct.
FS    = 15;
PAD   = 12;
BTN_H = 40;
BTN_W = 160;
INFO_H = 32;
CTRL_H = BTN_H + 2*PAD;

% ── Overlay panel ────────────────────────────────────────────────────────
app.PeakEditPanel = uipanel(app.UIFigure, ...
    'BorderType','line','BorderColor',app.clr_gold, ...
    'BackgroundColor',app.clr_bg, ...
    'Position',[0 0 FIG_W TAB_H], 'Visible','off');

% ── Info strip (top) ─────────────────────────────────────────────────────
app.PeakEditInfoLabel = uilabel(app.PeakEditPanel, ...
    'Text','', 'FontSize',FS, 'FontWeight','bold', ...
    'FontColor',app.clr_black, 'HorizontalAlignment','center', ...
    'Position',[PAD TAB_H-INFO_H-PAD FIG_W-2*PAD INFO_H]);

% ── Two axes ─────────────────────────────────────────────────────────────
AX_Y  = CTRL_H + PAD;
AX_H  = TAB_H - INFO_H - 3*PAD - CTRL_H;
WF_W  = round(0.36 * FIG_W);
EDIT_X = PAD + WF_W + PAD;
EDIT_W = FIG_W - EDIT_X - 2*PAD;

app.PeakEditWfAx = uiaxes(app.PeakEditPanel, ...
    'Position',[PAD AX_Y WF_W AX_H], 'BackgroundColor','white', 'Box','on');
disableDefaultInteractivity(app.PeakEditWfAx);
title(app.PeakEditWfAx, 'Waveform Stack', 'FontSize',13, 'FontWeight','bold');

app.PeakEditAx = uiaxes(app.PeakEditPanel, ...
    'Position',[EDIT_X AX_Y EDIT_W AX_H], 'BackgroundColor','white', 'Box','on');
disableDefaultInteractivity(app.PeakEditAx);

% ── Control bar (bottom) ─────────────────────────────────────────────────
app.PeakEditStatusLabel = uilabel(app.PeakEditPanel, ...
    'Text','', 'FontSize',FS-1, 'WordWrap','on', ...
    'Position',[PAD PAD FIG_W-4*(BTN_W+PAD)-PAD BTN_H]);

btn_x = FIG_W - 4*(BTN_W + PAD);
btn_colors = {[0.60 0.82 0.60], app.clr_btn, app.clr_btn, app.clr_gold};
btn_texts  = {'✓  Accept', '↩  Redo', '✕  Cancel', 'Done with Level  ▶'};
btn_vis    = {'off','off','off','on'};
btn_props  = {'PeakEditAcceptBtn','PeakEditRedoBtn','PeakEditCancelBtn','PeakEditDoneBtn'};
for bi = 1:4
    app.(btn_props{bi}) = uibutton(app.PeakEditPanel,'push', ...
        'Text',btn_texts{bi}, 'FontSize',FS-1, 'FontWeight','bold', ...
        'BackgroundColor',btn_colors{bi}, 'Visible',btn_vis{bi}, ...
        'Position',[btn_x+(bi-1)*(BTN_W+PAD) PAD BTN_W BTN_H]);
end
end
